import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cost Estimator",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: "/meta-image.jpg", 
        width: 1200, 
        height: 630,  
        alt: "Cost Estimator Preview", 
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
